import { NextResponse } from 'next/server'
import { getAgents } from '@/lib/agents'

// Re-read agents.json each request; it's regenerated by `agents-json`.
export const dynamic = 'force-dynamic'

export async function GET() {
  try {
    const agents = await getAgents()
    return NextResponse.json(agents)
  } catch (error) {
    return NextResponse.json(
      {
        error: 'Failed to read agents.json. Run `bun run agents:json` first.',
        message: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    )
  }
}
