import { readFile } from 'node:fs/promises'
import path from 'node:path'
import type { Agent } from '@clerk/eve-auth'

export type { Agent } from '@clerk/eve-auth'

// The agent graph generated by `bun run agents:json` (the `agents-json`
// command), dropped at the dashboard root. Override with AGENTS_JSON_PATH.
const AGENTS_PATH =
  process.env.AGENTS_JSON_PATH ?? path.join(process.cwd(), 'agents.json')

export async function getAgents(): Promise<Agent[]> {
  const raw = await readFile(AGENTS_PATH, 'utf8')
  return JSON.parse(raw) as Agent[]
}

export async function getAgent(id: string): Promise<Agent | undefined> {
  const agents = await getAgents()
  return agents.find(a => a.id === id)
}
