import { NextResponse } from 'next/server'
import { getAgent } from '@/lib/agents'

// Re-read agents.json each request; it's regenerated by `agents-json`.
export const dynamic = 'force-dynamic'

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  try {
    const agent = await getAgent(id)
    if (!agent) {
      return NextResponse.json(
        { error: `No agent with id "${id}".` },
        { status: 404 }
      )
    }
    return NextResponse.json(agent)
  } catch (error) {
    return NextResponse.json(
      {
        error: 'Failed to read agents.json. Run `bun run agents:json` first.',
        message: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    )
  }
}
